export const COURSES_MICROSERVICES = 'COURSES_MICROSERVICES';
export const coursesMessagePatterns = {
  CREATE_COURSE:'CREATE_COURSE',
  GET_ALL_COURSES: 'GET_ALL_COURSES',
  GET_ONE_COURSE: 'GET_ONE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  REMOVE_COURSE: 'REMOVE_COURSE',
}